steps:
  - id: 'Build Back stage'
    name: 'node:16-alpine3.15'
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        yarn install --frozen-lockfile
        yarn tsc
        yarn build
  
  - id: 'Build Backstage container'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg "POSTGRES_HOST=${_POSTGRES_HOST}" --build-arg "POSTGRES_PORT=${_POSTGRES_PORT}" --build-arg "POSTGRES_PASSWORD=${_POSTGRES_PASSWORD}" -t ${_IMAGE_NAME} -f packages/backend/Dockerfile .']

  - id: 'Generate tag'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker tag ${_IMAGE_NAME} us-east1-docker.pkg.dev/dhruv-development/backstage-dhruv-development/backstage:latest']

  - id: 'Push tag'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push us-east1-docker.pkg.dev/dhruv-development/backstage-dhruv-development/backstage:latest']


timeout: 1200s
logsBucket: ${_LOG_BUCKET}
tags: ['backstage']
substitutions:
  _IMAGE_NAME: 'backstage-dhruv-development'
logsBucket: '${_LOG_BUCKET}'
